services:
  jupyter:
    build: .
    container_name: jupyterspark
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./workspace:/workspace
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser